receivers:
  hostmetrics:
    scrapers:
      cpu:

processors:
  tagger:
    detectors: [ec2metadata]
exporters:
  logging:
    loglevel: debug
  awsemf:
    namespace: OTELProcessorMigration8
    region: us-west-2
    log_group_name: '/aws/ec2metadata/OTELProcessorMigration1'

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [taggerprocessor]
      exporters: [logging, awsemf]