receivers:
  hostmetrics:
    scrapers:
      cpu:

processors:
  ec2tagger:
exporters:
  logging:
    loglevel: debug
  awsemf:
    namespace: OTELProcessorMigration
    region: us-west-2
    log_group_name: '/aws/ec2/OTELProcessorMigration'

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [ec2tagger]
      exporters: [logging, awsemf]